# Paths
[srcPath]
content = "content"
blogOutPath = ".dist/blog"
indexOutPath = ".dist"
assetsPath = "assets"
template = "./templates/initial"
pdfOutPath = "documents"
hashesmetadata = "https://anubhavp.dev/metadata.json"

# MarkdownIt Options
[markdown]
enable = true
options = { html = true, breaks = true, linkify = true, typographer = true }

# Highlight.js Options
[highlight]
enable = true
defaultLanguage = "javascript"

# Date Formatting
[date]
format = "en-US"
options = { weekday = "long", month = "long", day = "numeric" }


[indexes]
tags = { tech = 0, life = 1, journal = 2, business = 3 }

# Podcast Configurations
[podcasts]

[[podcasts.featured]]
id = "278974813"
name = "Pop Culture Happy Hour"
slug = "pop-culture-happy-hour"
description = "NPR's entertainment and pop culture round-table podcast about movies, TV, music, books, and more."
